name: Mirror Jenkins Extractor

on:
  push:
    branches:
      - main
    paths:
      - 'tools/jenkins-extractor/**'
      - 'groovy-jenkins/**'
      - 'groovy-gdsl/**'
      - 'groovy-common/**'
      - 'groovy-build-tool/**'
      - 'infra/copybara/jenkins-extractor.bara.sky'
  workflow_dispatch:

jobs:
  copybara:
    runs-on: ubuntu-latest
    name: Run Copybara
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Run Copybara
        uses: Olivr/copybara-action@042b4395839f3a374a6455b541e29e40c949d717 # v1.2.5
        with:
          # Token must have 'repo' scope for the destination repository
          access_token: ${{ secrets.GLS_BOT_TOKEN }}
          config: infra/copybara/jenkins-extractor.bara.sky
          workflow: default
          # Identity for the committer (the bot)
          git_name: "gls-bot"
          git_email: "gls-bot@cavalcante.uk"