# OSV-Scanner checks dependencies for known vulnerabilities on PRs and on a schedule.
name: OSV-Scanner

on:
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 5 * * 1"

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  scan-scheduled:
    if: ${{ github.event_name == 'schedule' }}
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@375a0e8ebdc98e99b02ac4338a724f5750f21213 # v2.3.1
    with:
      scan-args: |-
        --include-git-root
        -r
        ./

  scan-pr:
    if: ${{ github.event_name == 'pull_request' }}
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@375a0e8ebdc98e99b02ac4338a724f5750f21213 # v2.3.1
    with:
      scan-args: |-
        --include-git-root
        -r
        ./
